### ISSUE TITLE
korean data format

### ISSUE THREAD

**Issue by wolfwork** [BurgerZ/WeatherM8-resources#131]
date month year - > year date month
6, 12m  -> 12m, 6d

example:
2017년 11월 14일  <-vaild
14 11월 2017 <- invaild
friday, 01/10/2018 <-invaild
2018/11/25, friday <- vaild

In Korean, please use this format.

**Comment by BurgerZ** [comment]
Well, create pull request with your changes in Korean language :)

**Comment by wolfwork** [comment]
I don't know how to show the date like ''25일''

**Comment by wolfwork** [comment]
Thank you @Lippe35

**Comment by Lippe35** [comment]
Its ok @wolfwork. Thanks for the help to @sdottaka too.
