### ISSUE TITLE
one space ?

### ISSUE THREAD

**Issue by Henry2o1o** [BurgerZ/WeatherM8-resources#188]
![image](https://user-images.githubusercontent.com/6131799/50060617-25a80000-0196-11e9-827c-195c4421e6e2.png)

![photo_2018-12-17_00-54-05](https://user-images.githubusercontent.com/6131799/50060636-6dc72280-0196-11e9-9775-1663124bf0b0.jpg)

Wind: O, 0m/s, one space

How can I change that?

**Comment by BurgerZ** [comment]
Hm, I guess this is from Weather BZ, not Weather M8?

**Comment by Henry2o1o** [comment]
I only have weather M8 installed.

This is a weather screen in the lock screen that uses M8.

**Comment by Henry2o1o** [comment]
I have various themes with weather indicator in the lock screen. That's the way it looks.

**Comment by Henry2o1o** [comment]
How would the string be for wind direction and wind force, for a widget?

**Comment by Henry2o1o** [comment]
uri="content://pro.burgerz.weather/weather" 

```
<Variable name="weather_wind_mi" type="string" column="wind" row="0"/>

<Var name="weather_wind" type="string" expression="ifelse(#hasweatherbz,@wind_text_st + @weather_wind_dir_bz + ', ' + #weather_wind_m_bz + @wind_speed_text,#hasweatherbz8,@wind_text_st + @weather_wind_bz8,@wind_text_st_mi + @weather_wind_mi)"
```

spaces insert ?

**Comment by BurgerZ** [comment]
> uri="content://pro.burgerz.weather/weather"

This provider Uri is for Weather BZ application.

> <Var name="weather_wind" type="string" expression="ifelse(#hasweatherbz,@wind_text_st + @weather_wind_dir_bz + ', ' + #weather_wind_m_bz + @wind_speed_text,#hasweatherbz8,@wind_text_st + @weather_wind_bz8,@wind_text_st_mi + @weather_wind_mi)"

Here your code checks for Weather BZ first, if found it uses its wind data, else if Weather M8 is found, it uses M8's wind data, which is "hardcoded" at the SQLite database (with space, I think, I have to check it).
