### ISSUE TITLE
Question about weather description

### ISSUE THREAD

**Issue by cjh3A5111** [BurgerZ/WeatherM8-resources#68]
Hello everyone, I have one question want to ask.
Please look at the three pictures below .

![1](https://user-images.githubusercontent.com/28937608/27937242-1bf5ffe2-62e8-11e7-9b65-7ef1e63329c9.jpg)
![2](https://user-images.githubusercontent.com/28937608/27937244-1d484134-62e8-11e7-82bd-5ed7a12033c6.jpg)
![3](https://user-images.githubusercontent.com/28937608/27937245-1e4d8d46-62e8-11e7-80df-1639a7f031d9.jpg)

Why the weather description still display clear(無雲) whichever day/night?
What have I done wrong?
Who can tell me what can I do?

P.S. 晴朗=Sunny  無雲=clear

**Comment by BurgerZ** [comment]
I've sent you a test apk. I think it's fixed. Reopen this issue if not.
